#!/bin/sh

GIT=git
TODAY="$(date +%Y-%m-%d)"

while getopts "fn" opt ; do
  case $opt in
    f) FLDIGI="fldigi" ;;
    n) GIT="" ;;
    *) exit 5 ;;
  esac
done
# shift away args
shift $((OPTIND - 1))

set -eu

git pull --ff-only
mkdir -p lotw/tmp

( set -x

  cd wsjtx
  ./import

  cd ../js8
  ./import

  if [ ${FLDIGI:-} ]; then
    cd ../fldigi
    ../bin/import-adif logbook.adif
  fi

  cd ../lotw
  LOG=tmp/df7cb-upload.adif
  STAMP=$(cat .upload.stamp || echo 'today')
  ../bin/export-adif $LOG $STAMP
  ./lotw-upload $STAMP
  ./clublog-upload $STAMP
  ./rrdxa-upload $STAMP
  ./dcl-upload $LOG
  ./eqsl-upload $LOG

  ../bin/export-adif tmp/df7cb-qo100.adif $STAMP "qso_via='QO100'"
  grep -q '<eor>' tmp/df7cb-qo100.adif && ./qo100-upload tmp/df7cb-qo100.adif

  echo "$TODAY" > .upload.stamp

  ./lotw_download
  ./dcl-download

  cd ../dump
  ./dump
)

if [ "$GIT" ]; then
  git add -u
  git commit -m "Log upload"
  git push
fi
