#!/bin/sh

GIT=git

while getopts "n" opt ; do
  case $opt in
    n) GIT="" ;;
    *) exit 5 ;;
  esac
done
# shift away args
shift $((OPTIND - 1))

set -eux

YEAR=$(date +%Y)

git pull --ff-only

( cd wsjtx; ./import )
( cd sql; ./dump )
( cd lotw
  ./export-adif $YEAR
  ./tqsl-upload df7cb-$YEAR.adif
  ./clublog-upload df7cb-$YEAR.adif
  ./eqsl-upload df7cb-$YEAR.adif &
)

if [ "$GIT" ]; then
  git add -u
  git commit -m "Log upload"
  git push
fi
