#!/bin/sh

GIT=git

while getopts "n" opt ; do
  case $opt in
    n) GIT="" ;;
    *) exit 5 ;;
  esac
done
# shift away args
shift $((OPTIND - 1))

trap "ssh feynman.df7cb.de -O exit" EXIT

set -eux

git pull --ff-only

ssh feynman.df7cb.de sleep 60 &
sleep 1

( cd wsjtx; ./import )
( cd js8; ./import )
( cd lotw
  LOG=df7cb-upload.adif
  ./export-adif $LOG $(cat .upload.stamp || echo 'today')
  ./tqsl-upload $LOG
  ./clublog-upload $LOG
  ./dcl-upload $LOG
  ./eqsl-upload $LOG
  echo "$(date +%Y-%m-%d)" > .upload.stamp
  ./lotw_download
)
( cd sql; ./dump )

if [ "$GIT" ]; then
  git add -u
  git commit -m "Log upload"
  git push
fi
