#!/bin/sh

set -eu

export PGSERVICE="cb"

psql -qX -c "TRUNCATE log2"

# start               stop                call   loc  qrg     mode rsttx rstrx mypwr comment
# 2020-05-01,13:40:30,2020-05-01,13:41:45,E73DN,JN93,2400.042815,FT8,+03,-05,,,

echo -n "wsjtx.log: "
< wsjtx.log \
  sed -e 's/,/ /' -e 's/,/ /2' -e 's/,$/,QO100/' |
  psql -X \
    -c "COPY log2 (start, stop, call, loc, qrg, mode, rsttx, rstrx, mypwr, comment, qso_via) FROM STDIN (FORMAT CSV, DELIMITER ',')"

echo -n "log: "
psql -X -c "INSERT INTO log
    SELECT * FROM log2 WHERE NOT EXISTS
        (SELECT * FROM log WHERE (log2.start, log2.call) = (log.start, log.call));"
