#!/bin/sh

PATH=$PATH:$(dirname $0)

set -eux

CONTEST="$1"
CBR="$2"

# add address and category info, remove decimal part of frequencies
export-cabrillo.py "$CONTEST" "$CBR"
sed -i \
  -e '/^CALLSIGN:/ a \
NAME: Christoph Berg\
EMAIL: cb@df7cb.de\
ADDRESS: Rather Str. 76a\
ADDRESS: 47802 Krefeld\
ADDRESS: Germany\
GRID-LOCATOR: JO31HI\
CLUB: Rhein Ruhr DX Association' \
  -e '/^CONTEST:/ a \
CATEGORY-ASSISTED: NON-ASSISTED\
CATEGORY-BAND: ALL\
CATEGORY-MODE: CW\
CATEGORY-OPERATOR: SINGLE-OP\
CATEGORY-POWER: LOW\
CATEGORY-STATION: FIXED\
CATEGORY-TRANSMITTER: ONE' \
  -e '/^QSO:/ s/\.[0-9]* / /' \
  $CBR

# fix missing trailing newline
echo >> $CBR

vi $CBR
git add $CBR
v commit -m "$CONTEST" --edit
