#!/bin/sh

CONTEST="$1"
LOG="$2"
CBR="${LOG%.log}.cbr"

set -eux

./import-tlf -n "$CONTEST" < $LOG
echo "Ok?"
read
./import-tlf "$CONTEST" < $LOG

./export-cabrillo "$CONTEST" "$CBR"
sed -i -e '/^QSO:/ s/\.[0-9]* / /' $CBR
