#!/bin/sh

set -eu

PATH=$PATH:$(dirname $0):$(dirname $0)/../bin

while getopts "ac:e:m:u" opt ; do
    case $opt in
        a) ASSISTED="-a" ;;
        c) CONTEST="$OPTARG" ;;
        e) EXTX="$OPTARG" ;;
        m) MYCALL="$OPTARG" ;;
        u) ASSISTED="-u" ;;
        *) exit 5 ;;
    esac
done
# shift away args
shift $(($OPTIND - 1))

: ${CONTEST:=MWC}
: ${EXTX:="#"}

LOG="${1:-$(date +%F)-$(echo $CONTEST | tr 'A-Z/ ' 'a-z__').log}"
CBR="${LOG%.*}.cbr"

[ -f "$LOG" ] || mv contest.log "$LOG"

set -eux

import-tlf ${EXTX:+-e "$EXTX"} ${MYCALL:+-m "$MYCALL"} -n "$CONTEST" "$LOG"
read ok
import-tlf ${EXTX:+-e "$EXTX"} ${MYCALL:+-m "$MYCALL"} "$CONTEST" "$LOG"

git add $LOG
export-cabrillo ${ASSISTED:-} "$CONTEST" "$CBR"
vi $CBR
git add $CBR
v commit -m "$CONTEST" --edit
