#!/usr/bin/python3

from decimal import Decimal
import getopt
import sys
import psycopg2

opts, args = getopt.getopt(sys.argv[1:], "n")
noop = False

for o, a in opts:
    if o == '-n':
        noop = True
    else:
        assert False, "Unknown option %s" % (o)

if not noop:
    conn = psycopg2.connect("service=cb")
    cur = conn.cursor()

#40CW  14-Apr-19 08:11 0002  LY3B           599  599  29            LY   29  0   7029.1

log = []
laststart = ''
for line in sys.stdin:

    # ; comment, append to last qso
    if line[0] == ';':
        if line[2:6] == 'via ':
            log[-1]['qsl_via'] = line[6:].rstrip().upper()
        else:
            log[-1]['comment'] = line[2:].rstrip()
        continue

    if line[23] != '0':
        Exception('serial does not start with 0')

    qso = { 'mycall': 'DF7CB',
            'mytrx': 'IC706',
            'mypwr': 100,
            'myant': 'FD4' }
    qso['mode'] = line[3:6].rstrip()
    qso['start'] = line[7:22] # date+time
    if laststart == qso['start']: # 2nd QSO in this minute
        qso['start'] += ':30'
    elif laststart == qso['start'] + ':30': # 3rd QSO in this minute
        qso['start'] += ':45'
    laststart = qso['start']
    qso['call'] = line[29:43].rstrip()
    qso['qrg'] = Decimal(line[79:87]) / 1000
    #qso['qrg'] = 7

    # my rst:
    qso['rsttx'] = line[44:47]+line[24:27] # my rst + serial (3 digits)
    #qso['rsttx'] = line[44:47]+'14'        # my rst + my WAZ/CQ zone
    #qso['rsttx'] = line[44:47]+'28'       # my rst + my ITU zone
    #qso['rsttx'] = line[44:47]+'42'       # my rst + my age
    #qso['rsttx'] = line[44:47]+'R10'      # my rst + my DOK
    #qso['rsttx'] = line[44:47]+'/CHRIS/NM' # my rst + my DOK
    #qso['rsttx'] = line[44:47]+'JO31'
    #qso['rsttx'] = line[24:27]+' CHRIS' # my serial (3 digits)
    #qso['rsttx'] = 'JO31'

    # their rst:
    qso['rstrx'] = line[49:52]+line[54:67].strip() # their rst + serial
    #qso['rstrx'] = line[49:52]+'/'+line[54:67].rstrip() # their rst / serial
    #qso['rstrx'] = line[54:64].rstrip()
    #qso['loc'] = line[56:64].rstrip()

    # multi
    #if line[68:76].rstrip() != '':
    #    qso['dok'] = line[68:76].rstrip()
    #qso['dok'] = line[54:67].rstrip()
    #qso['loc'] = line[54:67].rstrip()

    qso['contest'] = args[0] # contest name

    log.append(qso)

for qso in log:
    print (qso)

    if not noop:
        insert = "INSERT INTO log (" + \
            ', '.join(qso.keys()) + \
            ') VALUES (' + \
            ', '.join(['%s' for x in qso]) + \
            ')'
        args = [x for x in qso.values()]
        cur.execute(insert, args)

if not noop:
    conn.commit()
