#!/bin/bash

set -eu

PATH=$PATH:$(dirname $0):$(dirname $0)/../bin
CONTEST=""
MYCALL="DF7C"
ARGS=()

while getopts "ac:e:m:o:p:u" opt ; do
    case $opt in
        a) ASSISTED="-a" ;;
        c) ARGS+=(-c "$OPTARG") CONTEST="$OPTARG" ;;
        e) EXTX="$OPTARG" ;;
        m) ARGS+=(-m "$OPTARG") MYCALL="$OPTARG" ;;
        o) ARGS+=(-o "$OPTARG") ;;
        p) ARGS+=(-p "$OPTARG") ;;
        u) ASSISTED="-u" ;;
        *) exit 5 ;;
    esac
done
# shift away args
shift $(($OPTIND - 1))

case $CONTEST in
    CWT) EXTX="CHRIS 3484" ;;
esac

if [ "$CONTEST" ]; then
    LOG="${1:-$(date +%F)-$(echo $CONTEST | tr 'A-Z/ ' 'a-z__')-$(echo $MYCALL | tr 'A-Z/' 'a-z-').log}"
    ARGS+=(-e "${EXTX:-#}") # default to serial
else
    LOG="${1:-$(date +%F)-$(echo $MYCALL | tr 'A-Z/' 'a-z-').log}"
fi
[ -f "$LOG" ] || mv ${1:-contest.log} "$LOG"
CBR="${LOG%.*}.cbr"

set -eux

import-tlf "${ARGS[@]}" -n "$LOG"
read ok
import-tlf "${ARGS[@]}" "$LOG"
git add $LOG

[ "$CONTEST" ] || exit 0

export-cabrillo ${ASSISTED:-} "$CONTEST" "$CBR"
vi $CBR
git add $CBR
v commit -m "$CONTEST" --edit
