#!/bin/bash

set -eu
set -o pipefail

STAMP="${1:-yesterday}"
PW="$(cat $HOME/.priv/pw/clublog-app-pass)"
APIKEY="$(cat $HOME/.priv/pw/clublog-api-key)"

mkdir -p tmp

psql -AXtF ' ' -c "select mycall from log where last_update >= '$STAMP' group by 1 order by 1" service=cb | \
  while read MYCALL; do
    FILE="tmp/${MYCALL//\//-}.adif"
    echo "$MYCALL"

    ( set -x
      ../bin/export-adif $FILE $STAMP "mycall COLLATE \"C\" LIKE '$MYCALL%%'"

      curl -f -S \
        --form email=cb@df7cb.de \
        --form password=$PW \
        --form callsign=$MYCALL \
        --form file=@$FILE \
        --form api=$APIKEY \
        https://clublog.org/putlogs.php \
      || [ $? = 22 ] # ignore error 403 on re-upload of same file
    )
    echo
  done
