#!/bin/bash

set -eu

STAMP="${1:-yesterday}"
PASSWORD="$(cat ~/.priv/tqsl/password)"
export PGSERVICE=cb

mkdir -p tmp

psql -AXtF ' ' -c "select mycall, upper(myloc) from log where last_update >= '$STAMP' group by 1, 2 order by 1, 2" | \
  while read MYCALL MYLOC; do
    case $MYCALL in
      *DF7CB*|*DG8VD*|*DN3AJ*) ;;
      DA0RR) continue ;;
      *) echo "Won't upload for mycall $MYCALL"; exit 1 ;;
    esac
    FILE="tmp/${MYCALL//\//-}-$MYLOC.adif"
    echo "$MYCALL $MYLOC"
    ( set -x
      ../bin/export-adif $FILE $STAMP "mycall COLLATE \"C\" LIKE '$MYCALL%%' AND upper(myloc)='$MYLOC'"

      # exit 8 is "nothing to upload", exit 9 is "no new QSOs"
      tqsl -c "$MYCALL" -l "$MYLOC" --password="$PASSWORD" -u -a compliant $FILE -x
    ) || case $? in 8|9) ;; *) exit $?;; esac
  done
