#!/usr/bin/python3

import adif
import json
import psycopg2
import psycopg2.extras

adif = adif.ADIF()
lotw = adif.read('lotwreport.adi')

conn = psycopg2.connect("service=cb")
cur = conn.cursor(cursor_factory = psycopg2.extras.DictCursor)

# {'CALL': 'YB1BML', 'BAND': '30m', 'FREQ': '10.13828', 'MODE': 'FT8', 'QSO_DATE': '20190302', 'TIME_ON': '161500', 'QSL_RCVD': 'Y', 'DXCC': '327', 'COUNTRY': 'INDONESIA', 'IOTA': 'OC-021', 'GRIDSQUARE': 'OI33KO', 'CQZ': '28', 'ITUZ': '54'}

for qso in lotw:
    print(qso)
    cur.execute("""INSERT INTO lotw (start, call, qrg, mode, country, loc, info)
            VALUES (%s, %s, %s, %s, %s, %s, %s)
            ON CONFLICT (start, call) DO UPDATE
            SET qrg = EXCLUDED.qrg,
                mode = EXCLUDED.mode,
                country = EXCLUDED.country,
                loc = EXCLUDED.loc,
                info = EXCLUDED.info""",
            ("%s %s" % (qso['QSO_DATE'], qso['TIME_ON']),
            qso.get('CALL'),
            qso.get('FREQ'),
            qso.get('MODE'),
            qso.get('COUNTRY'),
            qso.get('GRIDSQUARE'),
            json.dumps(qso)))

conn.commit()
