#!/bin/bash

set -eu
set -o pipefail

STAMP="${1:-yesterday}"

mkdir -p tmp

psql -AXtF ' ' -c "select mycall from log where last_update >= '$STAMP' group by 1 order by 1" service=cb | \
  while read MYCALL; do
    FILE="tmp/${MYCALL//\//-}.adif"
    echo "$MYCALL"

    ( set -x
      ../bin/export-adif $FILE $STAMP "mycall = '$MYCALL'"

      curl --netrc -fsS --output /dev/null \
        --form station_callsign=$MYCALL \
        --form operator=DF7CB \
        --form logfile=@$FILE \
        https://logbook.rrdxa.org/log/upload/
    )
    echo
  done
