#!/bin/bash

set -eu
set -o pipefail

STAMP="${1:-yesterday}"

mkdir -p tmp

psql -AXtF ' ' -c "select mycall from log where last_update >= '$STAMP' group by 1 order by 1" service=cb | \
  while read MYCALL; do
    FILE="tmp/${MYCALL//\//-}.adif"
    echo "$MYCALL"

    ( set -x
      ../bin/export-adif $FILE $STAMP "mycall = '$MYCALL'"
      ./rrdxa-post "$FILE" "$MYCALL"
    )
    echo
  done
