#!/bin/sh

set -eu

FILE="$1"
QTH="Krefeld-Traar"
PASSWORD="$(cat ~/.priv/tqsl/password)"

set -x

# exit 9 is "no new QSOs"
tqsl -c DF7CB -l "$QTH" --password="$PASSWORD" -x -u -a compliant "$@" || [ $? = 9 ]
