#!/bin/sh

set -eu

export PGSERVICE="cb"

psql -qX -c "TRUNCATE log2"

# start               stop                call   loc    qrg   mode rsttx rstrx mypwr name
# 2019-12-09,20:23:10,2019-12-09,20:31:13,2W0RGA,IO81AP,7.079154,JS8,-10,-6,,Roy

echo -n "js8call.log: "
< js8call.log \
  sed -e 's/,/ /' -e 's/,/ /2' |
  psql -X \
    -c "COPY log2 (start, stop, call, loc, qrg, mode, rsttx, rstrx, mypwr, name) FROM STDIN (FORMAT CSV, DELIMITER ',')"

echo -n "log: "
psql -X -c "INSERT INTO log
    SELECT * FROM log2 WHERE NOT EXISTS
        (SELECT * FROM log WHERE (log2.start, log2.call) = (log.start, log.call));"
