#!/usr/bin/python3

import atexit
import psycopg2
import psycopg2.extras
import re
import readline

# PG

conn = psycopg2.connect("service=cb")
cur = conn.cursor(cursor_factory = psycopg2.extras.DictCursor)

# readline

histfile = '.history'
try:
    readline.read_history_file(histfile)
    # default history len is -1 (infinite), which may grow unruly
    readline.set_history_length(1000)
except FileNotFoundError:
    pass

atexit.register(readline.write_history_file, histfile)

# main

def update(qsl):
    args = (qsl['start'], qsl['call'])
    if qsl['qsltx'] == 'Y':
        sql = """UPDATE log SET qslrx = 'Y' WHERE (start, call) = (%s, %s)"""
    else: # qsl['qsltx'] in ('R', 'N'):
        sql = """UPDATE log SET qsltx = 'R', qslrx = 'Y' WHERE (start, call) = (%s, %s)"""
    print(sql % args)
    cur.execute(sql, args)
    conn.commit()

num = 1
while True:
    try:
        l = input('> ')
    except (EOFError, KeyboardInterrupt):
        print()
        exit()
    m = re.search("^[0-9]+$", l)
    if m:
        num = int(l)
        update(qsls[num])
        num += 1
    elif l == '':
        update(qsls[num])
        num += 1
    else:
        cur.execute("""SELECT row_number() OVER (ORDER BY start) AS n, * FROM log WHERE call ~* %s ORDER BY start""", (l,))
        qsls = [''] # numbers are 1-based
        for rec in cur.fetchall():
            qsls.append(rec)
            print("%d: %s \033[1m%s\033[0m %s %s %s %s \033[1m%s %s\033[0m %s %s" %
                    (rec['n'],
                    rec['start'], rec['call'], rec['qrg'], rec['mode'],
                    rec['rsttx'], rec['rstrx'],
                    rec['qsltx'], rec['qslrx'],
                    rec['contest'], rec['comment']))
        num = 1
